src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $parent_id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $photo;

    //Jointure
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Post", mappedBy="categories")
     */
    private $posts;


    //constructor
    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    //accesseurs
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    // jointures methods

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->addCategory($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            $post->removeCategory($this);
        }

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

// utilisation enum perso :

    const TYPE_VIDEO = 'Vidéo';
    const TYPE_POST = 'Post';
    /**
     * @ORM\Column(type="string", length=100)
     */
    private $post_type;


    const STATUS_OPEN = 'open';
    const STATUS_CLOSE = 'close';
    /**
     * @ORM\Column(type="string", length=100)
     */
    private $status;


// liaisons automatiques

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="post", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="posts", cascade={"persist"})
     * @ORM\JoinTable(name="post_category")
     */
    private $categories;




    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function setPrice($price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }



    public function getPostType(): ?string
    {
        return $this->post_type;
    }
/*
    public function setPostType(string $post_type): self
    {
        $this->post_type = $post_type;

        return $this;
    }
*/
    public function setPostType($post_type)
    {
        if (!in_array($post_type, array(self::TYPE_VIDEO, self::TYPE_POST))) {
            throw new \InvalidArgumentException("Invalid post_type");
        }
        $this->post_type = $post_type;
    }
    
    
    public function getStatus(): ?string
    {
        return $this->status;
    }
/*
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
*/
    public function setStatus($status)
    {
        if (!in_array($status, array(self::STATUS_OPEN, self:: STATUS_CLOSE))) {
            throw new \InvalidArgumentException("Invalid status");
        }
        $this->status = $status;
    }


//methodes jointure onetoone manytomany :

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category=null): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use App\Entity\Post;
use App\Form\ImageType;

//use Symfony\Component\Form\Extension\Core\Type\ImageType;
//use Symfony\Component\Form\Extension\Core\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label'=>'Titre', 
                'attr' => [
                    'placeholder'=>'Choisir un titre court et explicite',
                    ],
                'required' => true
                ])
                
            ->add('post_type', ChoiceType::class, [
                'label'=>'Type',
                'choices'  => [
                    'Post' => 'Post',
                    'Vidéo' => 'Vidéo',
                    ],
                'multiple' =>false,
                'expanded' =>true,
                'required' => true
                ])
              
            ->add('link', UrlType::class, [
                'label'=>'URL', 
                'attr' => [
                    'placeholder'=>'URL absolue de la vidéo'
                    ],
                'required'=>false
                ])

            ->add('duration', NumberType::class, [
                'label'=>'Durée', 
                'attr' => [
                    'placeholder'=>'Durée de la vidéo en minutes'
                    ],
                'required'=>false
                ])

            ->add('price', MoneyType::class, [
                'label'=>'Prix', 
                'attr' => [
                    'placeholder'=>'Utiliser le point et pas la virgule pour les décimales (ex : 20.00)'
                    ],
                'required'=>false
                ])

            ->add('content', TextareaType::class, [
                'label'=>'Contenu',
                'required' => true 
                ])
                
            ->add('status', ChoiceType::class, [
                'label'=>'Statut',
                'choices'  => [
                    'Publié' => 'open',
                    'Non publié' => 'close',
                    ],
                'multiple' =>false,
                'expanded' =>true,
                ])
                
            //->add('image', ImageType::class)
            /*
            ->add('file', FileType::class, [
                'required' => true
            ])
                */
                /*
            ->add('categories', ChoiceType::class, [
                'label'=>'Catégories',
                'choices'  => [
                    'Initiation' => 'Initiation',
                    'Perfectionnement' => 'Perfectionnement',
                    'Introduction' => 'Introduction',
                    'Les structures de données' => 'Les structures de données',
                    'Les classes' => 'Les classes',
                    'Init cat 4' => 'Init cat 4',
                    'Lambda' => 'Lambda',
                    'Compréhension de liste' => 'Compréhension de liste',
                    'Décorateur' => 'Décorateur',
                    'Perf cat 4' => 'Perf cat 4',
                    ],
                'multiple' =>true,
                'expanded' =>false,
                ])
                */
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\Image;
use App\Entity\Category;
use App\Form\PostType;
use App\Form\ImageType;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class PostController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard_post_index", methods={"GET"})
     * dashboard table page
     */
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('post/index.html.twig', ['posts' => $postRepository->findAll()]);
    }

      /**
     * @Route("/dashboard/post{id}", name="dashboard_post_show", methods={"GET"})
     * One post page
     */
    public function show(Post $post): Response
    {
        return $this->render('post/show.html.twig', ['post' => $post]);
    }

    /**
     * @Route("/dashboard/new", name="dashboard_post_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash('success', "Le post ".$post->getTitle()." a bien été ajouté.");

            return $this->redirectToRoute('dashboard_post_index');
        }

        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/dashboard/post{id}/edit", name="dashboard_post_edit", methods={"GET","POST"})
     */
    public function edit(PostRepository $postRepository, Request $request, Post $post, $id): Response
    {
        /*
        $em=$this->getDoctrine()->getManager();
        $post=$em->getRepository('App:Post')->find($id);
        if(null===$post){
            $this->addFlash('error', "Le post ".$post->getTitle()." n'existe pas.");
        }
        $listCategories=$em->getRepository('App:Category')->findAll();
        foreach($listCategories as $category) {
            $post->addCategory($category);
        }
        $em->flush();
*/
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', "Le post ".$post->getTitle()." a bien été modifié.");

            return $this->redirectToRoute('dashboard_post_show', ['id' => $post->getId()]);
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/dashboard/post{id}/delete", name="dashboard_post_delete", methods={"DELETE"})
     */
    public function delete(PostRepository $postRepository, Request $request, Post $post): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($post);
            $entityManager->flush();

            $this->addFlash('success', "Le post ".$post->getTitle()." a bien été supprimé.");
        }

        return $this->redirectToRoute('dashboard_post_index');
    }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('dashboard_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Êtes-vous certain de vouloir effacer ce post ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-outline-danger btn-sm mr-2"><i class="fas fa-trash text-danger pr-2"></i> Effacer</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-primary btn-sm mr-2"><i class="fas fa-save text-primary pr-2"></i> {{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Post {{ post.id }} - Modification{% endblock %}

{% block pageName %}
    <h2 class="text-center">Modification du post « {{ post.title }} »</h2>
{% endblock %}

{% block content %}
    <main class="container-fluid"> 
        <div class="row"><!--start form post content-->
            <div class="col-12 col-sm-8 offset-sm-1"><!--start currentpost block-->       
                <nav class="pt-2 col-12 "><!--start breadcrumb-->
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{path('index')}}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{{path('dashboard_post_index')}}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Modification de « {{ post.title }} »</li>
                    </ol>
                </nav><!--end breadcrumb-->

                <div class="col-12 col-md-8 offset-md-1"><!--start form content-->
                    {{ include('post/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

                    <p>{{ include('post/_delete_form.html.twig') }}</p>
                </div><!--end form content-->
            </div><!--end currentpost block-->
            <div class="pt-2 col-12 col-md-3"><!--start yellow button block-->
                    <a href="{{ path('dashboard_post_index') }}" class="btn btn-warning ml-auto text-secondary mb-4" ><i class="fas fa-user-circle text-primary pr-2"></i>Retour au tableau de bord</a>
            </div><!--end yellow button block-->
        </div><!--end form post content-->
    </main>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} - Dashboard{% endblock %}
{% block pageName %}
    <h2 class="text-center">Dashboard - Vidéos / posts </h2>
{% endblock %}

{% block nav %}
                {{parent()}}
{% endblock %}

{% block content %}
    <main class="container-fluid">
        <div class="row"><!--start post content-->
            <div class="col-12 col-sm-8"><!--start currentpost block-->       
                <nav class="pt-2 col-12 col-md-4 offset-md-1"><!--start breadcrumb--> 
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{path('index')}}">Accueil</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </nav><!--end breadcrumb--> 
            </div>
            <div class="pt-2 col-12 col-md-3">
                    <a href="{{ path('dashboard_post_new') }}" class="btn btn-warning ml-auto text-secondary mb-4" ><i class="fas fa-plus text-primary pr-2"></i>Ajouter un nouveau post</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table mx-3 table-bordered table-striped">
                <thead class="table-dark">
                    <tr>
                        <th>Id</th>
                        <th>Image</th>
                        <th>Titre</th>
                        <th>URL</th>
                        <th>Durée (min)</th>
                        <th>Date de création</th>
                        <th>Prix</th>
                        <!--<th>Description</th>-->
                        <th>Type</th>
                        <th>Statut</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><img src="{{ post.image.link }}" width="60" height="40"></td>
                        <td>{{ post.title }}</td>
                        <td>{{ post.link }}</td>
                        <td>{{ post.duration }}</td>
                        <td>{{ post.date ? post.date|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ post.price }}</td>
                        <!--<td>{#{{ post.content }}#}</td>-->
                        <td>{{ post.postType }}</td>
                        <td>{{ post.status }}</td>
                        <td>
                            <a href="{{ path('dashboard_post_show', {'id': post.id}) }}" class="btn btn-sm btn-outline-primary mr-2 mb-2"><i class="fas fa-eye text-primary pr-2"></i>Voir</a>
                            <a href="{{ path('dashboard_post_edit', {'id': post.id}) }}" class="btn btn-sm btn-outline-primary mr-2 mb-2"><i class="fas fa-edit text-primary pr-2"></i>Modifier</a> 
                            {{ include('post/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="10">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} - Ajouter un nouveau Post{% endblock %}

{% block pageName %}
    <h2 class="text-center">Ajouter un nouveau Post</h2>
{% endblock %}

{% block content %}
<main class="container-fluid"> 
        <div class="row"><!--start form post content-->
            <div class="col-12 col-sm-8 offset-sm-1"><!--start new post block-->       
                <nav class="pt-2 col-12 "><!--start breadcrumb-->
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{path('index')}}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{{path('dashboard_post_index')}}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Ajouter un nouveau Post</li>
                    </ol>
                </nav><!--end breadcrumb-->

                <div class="col-12 col-md-8 offset-md-1 mb-4"><!--start form content-->
                    {{ include('post/_form.html.twig') }}
                </div><!--end form content-->
            </div><!--end new post block-->
            <div class="pt-2 col-12 col-md-3"><!--start yellow button block-->
                <a href="{{ path('dashboard_post_index') }}" class="btn btn-warning ml-auto text-secondary mb-4" ><i class="fas fa-user-circle text-primary pr-2"></i>Retour au tableau de bord</a>
            </div><!--end yellow button block-->
        </div><!--end form post content-->
</main>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Post {{ post.id }}{% endblock %}

{% block pageName %}
    <h2 class="text-center">Post {{ post.title }}</h2>
{% endblock %}

{% block content %}
    <main class="container-fluid"> 
        <div class="row"><!--start page content-->
            <div class="col-12 col-sm-8 offset-sm-1"><!--start currentpost block-->       
                <nav class="pt-2 col-12 "><!--start breadcrumb--> 
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{path('index')}}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{{path('dashboard_post_index')}}">Dashboard</a></li>
                        <li class="breadcrumb-item active">{{ post.title }}</li>
                    </ol>
                </nav><!--end breadcrumb-->

                <div class="col-12 col-md-8 offset-md-3"><!--start post content list block-->
                    <ul class="list-unstyled boldUpper">
                        <li class="text-primary"><span> Titre :</span><strong> {{ post.title }}</strong></li>
                        <li><span> Post Id :</span> {{ post.id }}</li>
                        <li><span> Date de creation :</span> {{ post.date ? post.date|date('Y-m-d H:i:s') : '' }}</li>
                        <li><span> Contenu :</span> {{ post.content }}</li>
                        <li><span> Type :</span> {{ post.postType }}</li>
                        <li><span> Lien vidéo :</span> {{ post.link }}</li>
                        <li><span> Durée vidéo :</span> {{ post.duration }} minutes</li>
                        <li><span> Prix :</span> {{ post.price }} €</li>
                        <li><span> Mise en ligne :</span> {{ post.status }}</li>

                        {% for category in post.categories %}
                            {% if category.parentId %}
                                <li><span> Catégorie principale :</span> {% if (category.parentId == 1) %}Initiation{% else %}Perfectionnement{% endif %}</li>
                            {% endif %}
                            <li><span> Catégorie :</span> {{ category.name }}</li>
                        {% endfor %}
                        <li class="mb-4"><span> Image liée :</span> </br>NOM : {{ post.image.title }}, </br>
                        URL : {{ post.image.link }},  </br>DIMENSIONS : {{ post.image.dimension }}</li>
                        <img src="{{ post.image.link }}">
                    </ul>

                    <p><a href="{{ path('post', {'id': post.id}) }}" class="btn btn-sm btn-outline-primary mr-2"><i class="fas fa-edit text-primary pr-2"></i>Afficher la version en ligne</a> <a href="{{ path('dashboard_post_edit', {'id': post.id}) }}" class="btn btn-sm btn-outline-primary mr-2"><i class="fas fa-edit text-primary pr-2"></i>Modifier</a> {{ include('post/_delete_form.html.twig') }}</p>
                </div><!--end post content list block-->
            </div><!--end currentpost block-->

            <div class="pt-2 col-12 col-md-3"><!--start yellow button block-->
                    <a href="{{ path('dashboard_post_index') }}" class="btn btn-warning ml-auto text-secondary mb-4" ><i class="fas fa-user-circle text-primary pr-2"></i>Retour au tableau de bord</a>
            </div><!--end yellow button block-->
        </div><!--end page content-->
    </main>
{% endblock %}